Added rdfs:comment for bibo:issue
vivo-ontologies/vivo-ontology pull request #1
Opened 2022-05-02 13:58 UTC by hauschke

A rdfs:comment for bibo:issue was added. Definition was taken from http://gbol.life/ontology/bibo/Issue/.

2024-05-22 14:07 UTC, chenejac requested changes
@hauschke please check my suggestion

2024-05-22 14:07 UTC, chenejac commented on vivo.owl
> +	<rdfs:comment xml:lang="en"Something that is printed or published and distributed, esp. a given number of a periodical.</rdfs:comment>
```suggestion
	<rdfs:comment xml:lang="en">Something that is printed or published and distributed, esp. a given number of a periodical.</rdfs:comment>
```

2024-05-22 14:08 UTC, brianjlowe requested changes
Tag seems to be missing a greater-than character after "en": <rdfs:comment xml:lang="en"Something

2024-06-05 14:11 UTC, brianjlowe approved these changes

2024-06-10 11:42 UTC, chenejac approved these changes
@hauschke thanks

2024-06-10 11:43 UTC, merged